### ISSUE TITLE
why do you use Zero Copy

### ISSUE THREAD

**Issue by HoangNgo88** [ned14/zero-copy-socket-test#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Zero Copy in your project instead of others, are there any special feature in Zero Copy. Can you share me about it. What is the advantage and disadvantage of Zero Copy. Thanks

**Comment by ned14** [comment]
The repo contains some benchmarking code which might have been useful for systems eight years ago. It has examples of using zero copy networking to see what performance difference there is.

If you need to learn more about zero copy networking, https://en.wikipedia.org/wiki/Zero-copy is a good start.
